from app import create_app, db
from app.model.workout_name import WorkoutName


WORKOUT_NAMES = [
    # Cardio / Endurance
    "Running",
    "Tempo Run",
    "Interval Run",
    "Long Run",
    "Trail Run",
    "Sprints",
    "Hill Sprints",
    "5K Run",
    "10K Run",
    "Half Marathon",
    "Marathon Training",
    "Cycling",
    "Road Cycling",
    "Mountain Biking",
    "Spinning",
    "Spinning – Hills",
    "Spinning – Intervals",
    "Cycling HIIT",
    "Swimming",
    "Swimming – Freestyle",
    "Swimming – Breaststroke",
    "Swimming – Butterfly",
    "Swimming – Backstroke",
    "Swimming – Intervals",
    "Swimming – Drills",
    "Rowing",
    "Row Erg",
    "Row Intervals",
    "Row HIIT",
    "Ski Erg",
    "Assault Bike",
    "Air Bike Intervals",
    "Elliptical",
    "Jump Rope",
    "Double Unders",
    "Walking",
    "Power Walking",
    "Hiking",
    "Trail Hiking",
    "Stair Climbing",
    "Stair Master",
    "Boxing",
    "Kickboxing",
    "Shadow Boxing",
    "Heavy Bag Work",
    "Speed Bag",
    # Strength Training - Upper Body Push
    "Bench Press",
    "Incline Bench Press",
    "Decline Bench Press",
    "Dumbbell Bench Press",
    "Close-Grip Bench Press",
    "Military Press",
    "Overhead Press",
    "Seated Shoulder Press",
    "Arnold Press",
    "Push Press",
    "Push-ups",
    "Diamond Push-ups",
    "Decline Push-ups",
    "Incline Push-ups",
    "Handstand Push-ups",
    "Dips",
    "Chest Dips",
    "Tricep Dips",
    "Lateral Raises",
    "Front Raises",
    "Tricep Extensions",
    "Skull Crushers",
    "Cable Pushdowns",
    # Strength Training - Upper Body Pull
    "Pull-ups",
    "Chin-ups",
    "Neutral Grip Pull-ups",
    "Wide Grip Pull-ups",
    "Assisted Pull-ups",
    "Lat Pulldown",
    "Close Grip Lat Pulldown",
    "Behind Neck Pulldown",
    "Seated Cable Rows",
    "Bent Over Rows",
    "Pendlay Rows",
    "Single-Arm Dumbbell Rows",
    "T-Bar Rows",
    "Face Pulls",
    "Upright Rows",
    "Shrugs",
    "Bicep Curls",
    "Hammer Curls",
    "Preacher Curls",
    "Concentration Curls",
    "Cable Curls",
    "21s Bicep Curls",
    # Strength Training - Lower Body
    "Back Squat",
    "Front Squat",
    "Overhead Squat",
    "Box Squat",
    "Pause Squat",
    "Bulgarian Split Squat",
    "Goblet Squat",
    "Deadlift",
    "Romanian Deadlift",
    "Sumo Deadlift",
    "Deficit Deadlift",
    "Single-Leg Deadlift",
    "Good Mornings",
    "Hip Thrust",
    "Single-Leg Hip Thrust",
    "Glute Bridge",
    "Leg Press",
    "Hack Squat",
    "Lunges",
    "Walking Lunges",
    "Reverse Lunges",
    "Side Lunges",
    "Step-ups",
    "Box Jumps",
    "Leg Extensions",
    "Leg Curls",
    "Standing Calf Raises",
    "Seated Calf Raises",
    "Donkey Calf Raises",
    # Olympic Weightlifting
    "Clean",
    "Power Clean",
    "Hang Clean",
    "Clean and Jerk",
    "Split Jerk",
    "Push Jerk",
    "Snatch",
    "Power Snatch",
    "Hang Snatch",
    "Clean Pulls",
    "Snatch Pulls",
    "Muscle Snatch",
    # Functional / CrossFit
    "CrossFit WOD",
    "AMRAP Workout",
    "EMOM Workout",
    "Tabata",
    "HIIT",
    "Circuit Training",
    "Burpees",
    "Mountain Climbers",
    "Turkish Get-ups",
    "Wall Balls",
    "Thrusters",
    "Devil Press",
    "Man Makers",
    "Kettlebell Swings",
    "Russian Kettlebell Swings",
    "American Kettlebell Swings",
    "Kettlebell Clean and Press",
    "Kettlebell Snatch",
    "Medicine Ball Slams",
    "Battle Ropes",
    "Sled Push",
    "Sled Pull",
    "Prowler Push",
    "Tire Flips",
    "Farmer's Walk",
    "Overhead Carries",
    "Sandbag Training",
    "Rope Climbs",
    # Core / Abs
    "Plank",
    "Side Plank",
    "Plank Walks",
    "Ab Rollouts",
    "Crunches",
    "Bicycle Crunches",
    "Reverse Crunches",
    "V-ups",
    "Hollow Holds",
    "Dragon Flags",
    "Russian Twist",
    "Windshield Wipers",
    "Hanging Leg Raises",
    "Cable Woodchops",
    "Pallof Press",
    "Bird Dogs",
    "Dead Bugs",
    "Superman Holds",
    # Flexibility / Recovery
    "Yoga",
    "Power Yoga",
    "Vinyasa Flow",
    "Yin Yoga",
    "Hot Yoga",
    "Pilates",
    "Mat Pilates",
    "Reformer Pilates",
    "Mobility Work",
    "Dynamic Stretching",
    "Static Stretching",
    "PNF Stretching",
    "Foam Rolling",
    "Myofascial Release",
    "Active Recovery",
    # Sport-Specific
    "Basketball",
    "Soccer",
    "Tennis",
    "Volleyball",
    "Rock Climbing",
    "Bouldering",
    "Martial Arts",
    "BJJ",
    "Wrestling",
    "Baseball",
    "Golf",
]


def main() -> None:
    """Populate the global workout_name catalogue with popular workouts.

    Safe to run multiple times – duplicates are ignored.
    """
    app = create_app()
    with app.app_context():
        inserted = 0
        for name in WORKOUT_NAMES:
            exists = WorkoutName.query.filter_by(name=name, user_id=None).first()
            if not exists:
                db.session.add(WorkoutName(name=name))
                inserted += 1
        if inserted:
            db.session.commit()
        print(
            f"Inserted {inserted} new workout names. Total rows now: {WorkoutName.query.count()}"
        )


if __name__ == "__main__":
    main()
