"""Enlarge user.password for hashed values

Revision ID: 022a1b00b7ae
Revises: 9215e8d96d5b
Create Date: 2025-07-30 16:00:49.989281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022a1b00b7ae'
down_revision = '9215e8d96d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
