"""add password to user schema

Revision ID: 194b1527b7b2
Revises: cc9fbd0b5fa0
Create Date: 2025-07-13 13:09:54.618902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194b1527b7b2'
down_revision = 'cc9fbd0b5fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
