"""added workout db

Revision ID: 97b5ff3267be
Revises: 194b1527b7b2
Create Date: 2025-07-13 13:27:51.903461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b5ff3267be'
down_revision = '194b1527b7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_date', sa.Date(), nullable=False),
    sa.Column('workout_type', sa.String(length=80), nullable=False),
    sa.Column('workout_duration', sa.Integer(), nullable=False),
    sa.Column('workout_distance', sa.Float(), nullable=False),
    sa.Column('workout_calories', sa.Integer(), nullable=False),
    sa.Column('workout_notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout')
    # ### end Alembic commands ###
