"""add workout_name table and FK to workout

Revision ID: df22c99f1930
Revises: eaa9abd48e1c
Create Date: 2025-07-30 11:28:32.261872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df22c99f1930'
down_revision = 'eaa9abd48e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'workout_name', ['name_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('name_id')

    op.drop_table('workout_name')
    # ### end Alembic commands ###
